[package]

name = "cpclib-crunchers"
version = "0.7.0"
description = "crunchers that are used in cpc world"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
libc.workspace = true

[build-dependencies]
built.workspace = true
cc.workspace = true

#[lib]
#crate-type = ["cdylib", "dylib"]
