[package]
name = "cpclib-integration-tests"
version = "0.11.0"
authors = ["Krusty/Benediction <krusty@cpcscene.com>"]
edition = "2021"
rust-version = "1.74"

[dependencies]
# CLI tool libraries
cpclib-basm = { workspace = true, default-features = true }
cpclib-bdasm = { workspace = true, default-features = true }
cpclib-basmdoc = { workspace = true, default-features = true, features = ["generator"] }
cpclib-borgams = { workspace = true, default-features = true }
cpclib-catalog = { workspace = true, default-features = true }
cpclib-locomotive = { workspace = true, default-features = true }
cpclib-cprcli = { workspace = true, default-features = true }
cpclib-cslcli = { workspace = true, default-features = true }
cpclib-xfertool = { workspace = true, default-features = true }
cpclib-imgconverter = { workspace = true, default-features = true }
cpclib-bndbuild = { workspace = true, default-features = true }
cpclib-sna = { workspace = true, features = ["cmdline", "interactive"] }

# For clap Command validation
clap = { workspace = true }
regex = { workspace = true }
