id = "cpclib-lsp-zed"
name = "CPClib - Amstrad CPC Development"
version = "0.0.1"
schema_version = 1
authors = ["Krusty Benediction <krusty.benediction@gmail.com>"]
description = "Language support for Amstrad CPC development: Z80 assembly (basm), bndbuild, Locomotive BASIC"
repository = "https://github.com/cpcsdk/rust.cpclib"

snippets = ["./snippets/basm.json", "./snippets/bndbuild.json"]

[language_servers.cpclib-lsp]
name = "CPClib LSP"
languages = ["Basm", "Bndbuild", "Locomotive BASIC", "CatArt BASIC"]

[language_servers.cpclib-lsp.language_ids]
"Basm" = "basm"
"Bndbuild" = "bndbuild"
"Locomotive BASIC" = "locomotive-basic"
"CatArt BASIC" = "catart-basic"
