[package]
name = "cpclib-bdasm"
version = "0.7.1"
description = "Z80 disassembler. Still contains some bugs."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpclib-asm.workspace = true
cpclib-disc.workspace = true
clap.workspace = true
lazy_static.workspace = true
time = "0.3.29"

[build-dependencies]
built = { version = "0.6.1", features = ["chrono"] }

[[bin]]
name = "bdasm"
path = "src/main.rs"

