[package]
name = "cpclib-bdasm"
version = "0.6.1-alpha.2"
description = "Z80 disassembler. Still contains some bugs."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpclib-asm = "0.6.1-alpha.2"
cpclib-disc = "0.6.1-alpha.2"
clap = "3.1.18"
time = "0.3.9"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }

[[bin]]
name = "bdasm"
path = "src/main.rs"

