brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
edition = "2021"
fn_params_layout = "Tall"
force_multiline_blocks = true
format_strings = false
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
indent_style = "Block"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
remove_nested_parens = true
reorder_modules = true
space_after_colon = true
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
where_single_line = true