[package]
name = "cpclib-asmfmt"
version.workspace = true
description = "Assembly source code formatter for basm Z80 assembly"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-asm.workspace = true
cpclib-common.workspace = true
fs-err.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
bon.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }

[features]
cmdline = ["dep:clap"]

[[bin]]
name = "basm-fmt"
path = "src/main.rs"
required-features = ["cmdline"]
