def tokenize(code: str) -> bytes: ...
def detokenize(data: bytes) -> str: ...
def line_numbers(code: str) -> list[int]: ...
from .sna import Snapshot

def to_snapshot(code: str) -> Snapshot: ...
def basic_info() -> str: ...
