from typing import Self

from ._types import OutputCallback

class Task:
    """One bndbuild task: `Task("basm toto.asm -o toto.o")` or `Task("basm", ["toto.asm", "-o", "toto.o"])`.

    Every tool bndbuild knows (img2cpc, imgconverter, dsk, hideur, xfer, ...) is
    reachable this way."""

    def __init__(self, task: str, args: list[str] | None = None) -> None: ...
    def execute(
        self, on_output: OutputCallback | None = None, capture: bool = False
    ) -> dict[str, str] | None:
        """Runs the task. Its output goes to the console, or to `on_output(kind, text)`.
        With `capture=True`, returns `{"stdout": ..., "stderr": ...}`."""

class SnapshotBuilder:
    def __init__(self) -> None: ...
    def in_snapshot(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def set_token(self, token: str, value: str) -> Self: ...
    def put_data(self, address: int, byte: int) -> Self: ...
    def load(self, file: str, address: str) -> Self: ...
    def version(self, ver: str) -> Self: ...
    def build(self) -> Task: ...

class ArkosTracker3Builder:
    def __init__(self) -> None: ...
    def input(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def arg(self, arg: str) -> Self: ...
    def build(self) -> Task: ...

class ChipnsfxBuilder:
    def __init__(self) -> None: ...
    def input(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def arg(self, arg: str) -> Self: ...
    def build(self) -> Task: ...

class MinyBuilder:
    def __init__(self) -> None: ...
    def input(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def build(self) -> Task: ...

class AytBuilder:
    def __init__(self) -> None: ...
    def input(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def build(self) -> Task: ...

class SongConverterBuilder:
    def __init__(self, converter_type: str) -> None: ...
    def input(self, path: str) -> Self: ...
    def output(self, path: str) -> Self: ...
    def arg(self, arg: str) -> Self: ...
    def build(self) -> Task: ...

def bndbuild_info() -> str: ...
