class Cartridge:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> Cartridge: ...
    @staticmethod
    def from_bytes(data: bytes) -> Cartridge: ...
    def banks(self) -> list[int]: ...
    def bank(self, number: int) -> bytes: ...
    def set_bank(self, number: int, data: bytes) -> None: ...
    def remove_bank(self, number: int) -> bool: ...
    def save(self, path: str) -> None: ...
    def to_bytes(self) -> bytes: ...

def cpr_info() -> str: ...
