class CompressionResult:
    @property
    def format(self) -> str: ...
    @property
    def data(self) -> bytes: ...
    @property
    def delta(self) -> int | None: ...
    def __len__(self) -> int: ...

def formats() -> list[str]: ...
def compress(
    data: bytes, format: str, timeout: float | None = None
) -> CompressionResult: ...
def compare(
    data: bytes, formats: list[str] | None = None, timeout: float | None = None
) -> list[tuple[str, int | None, str | None]]: ...
def crunchers_info() -> str: ...
