from types import TracebackType

class Emulator:
    def __init__(
        self,
        emulator: str = "ace",
        snapshot: str | None = None,
        drive_a: str | None = None,
        drive_b: str | None = None,
        headless: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    def type_text(self, text: str) -> None: ...
    def read_memory(self, address: int, count: int) -> bytes: ...
    def write_memory(self, address: int, data: bytes) -> None: ...
    def load_snapshot(self, path: str) -> None: ...
    def load_disc(self, path: str, drive: int = 0) -> None: ...
    def save_disc(self, drive: int = 0) -> bytes: ...
    def screenshot(self) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> Emulator: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc: BaseException | None = None,
        tb: TracebackType | None = None,
    ) -> None: ...

def emulators() -> list[str]: ...
