from typing import Any

def default_options() -> dict[str, Any]: ...
def format_source(code: str, options: dict[str, Any] | None = None) -> str: ...
def format_range(
    code: str, start_line: int, end_line: int, options: dict[str, Any] | None = None
) -> str: ...
