from ._types import OutputCallback

class MusicBuild:
    @property
    def player(self) -> str: ...
    @property
    def program(self) -> bytes: ...
    @property
    def program_bytes(self) -> int: ...
    @property
    def load_address(self) -> int: ...
    @property
    def song_bytes(self) -> int | None: ...
    @property
    def player_bytes(self) -> int | None: ...
    @property
    def buffer_bytes(self) -> int | None: ...
    @property
    def play_nops(self) -> int | None: ...
    @property
    def snapshot(self) -> str | None: ...

class PlayerComparison:
    @property
    def player(self) -> str: ...
    @property
    def error(self) -> str | None: ...
    @property
    def build(self) -> MusicBuild | None: ...

def players() -> list[str]: ...
def compatible_players(song: str) -> list[str]: ...
def song_info(song: str) -> dict[str, object]: ...
def build(
    song: str,
    player: str | None = None,
    snapshot: str | None = None,
    name: str | None = None,
    sid_wait_line_count: int = 72,
    on_output: OutputCallback | None = None,
) -> MusicBuild: ...
def build_dsk(
    song: str,
    dsk: str,
    player: str | None = None,
    name: str | None = None,
    sid_wait_line_count: int = 72,
    on_output: OutputCallback | None = None,
) -> str: ...
def play(
    song: str,
    emulator: str = "ace",
    player: str | None = None,
    name: str | None = None,
    sid_wait_line_count: int = 72,
    on_output: OutputCallback | None = None,
) -> str: ...
def compare(
    song: str, name: str | None = None, on_output: OutputCallback | None = None
) -> list[PlayerComparison]: ...
def compare_table(
    song: str, name: str | None = None, on_output: OutputCallback | None = None
) -> str: ...
