class Snapshot:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> Snapshot: ...
    @staticmethod
    def from_bytes(data: bytes) -> Snapshot: ...
    @property
    def version(self) -> int: ...
    @property
    def memory_kb(self) -> int: ...
    def get(self, flag: str) -> int | list[int]: ...
    def set(self, flag: str, value: int) -> None: ...
    def flags(self) -> dict[str, int | list[int]]: ...
    def memory(self) -> bytes: ...
    def read(self, address: int, count: int) -> bytes: ...
    def write(self, address: int, data: bytes) -> None: ...
    def load_file(self, path: str, address: int) -> None: ...
    def chunks(self) -> list[str]: ...
    def save(self, path: str, version: int = 2) -> None: ...
    def to_bytes(self, version: int = 2) -> bytes: ...
