# Generated by dev/gen_tools_stub.py from `tools.commands()`: one function per
# tool (and per alias that is a valid Python name). Tools such as `2cdt` are
# reached with `run("2cdt", ...)`.
from typing import Any

from ._types import OutputCallback

def commands() -> list[dict[str, Any]]: ...
def run(
    command: str,
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None: ...

def basm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble Z80 source code using basm (built-in assembler)."""

def assemble(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble Z80 source code using basm (built-in assembler)."""

def orgams(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble using Orgams assembler syntax."""

def rasm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble using Rasm assembler."""

def sjasmplus(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble using SjASMPlus assembler."""

def vasm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Assemble using vasm assembler."""

def vlink(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Link object files using vlink linker."""

def bdasm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Disassemble Z80 binary code."""

def dz80(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Disassemble Z80 binary code."""

def disark(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Disassemble using Disark."""

def uz80(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Disassemble using uz80."""

def basmdoc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Generate documentation from basm source."""

def doc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Generate documentation from basm source."""

def ace(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in ACE emulator."""

def acedl(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in ACE emulator."""

def cpcec(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in CPCEC emulator."""

def sugarbox(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in Sugarbox emulator."""

def winape(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in WinAPE emulator."""

def retrovm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in RetroVirtual Machine emulator."""

def rvm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in RetroVirtual Machine emulator."""

def amspirit(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in AmSpirit emulator."""

def amspiritlite(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in AMSpiriT Lite, the portable AMSpiriT build."""

def amspirit_lite(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in AMSpiriT Lite, the portable AMSpiriT build."""

def lite(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in AMSpiriT Lite, the portable AMSpiriT build."""

def cpcemu(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in CPCEmu emulator."""

def cpc_emu(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in CPCEmu emulator."""

def cpcemupower(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in CPCEmuPower emulator."""

def caprice(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in Caprice Forever emulator."""

def cadence(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run in Cadence emulator."""

def dsk(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or modify DSK disk images."""

def disc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or modify DSK disk images."""

def sna(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or modify SNA snapshot files."""

def snpashot(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or modify SNA snapshot files."""

def catalog(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """List disk catalog."""

def cat(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """List disk catalog."""

def impdsk(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """ImpDisk disk operations."""

def impdisc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """ImpDisk disk operations."""

def hxcfe(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """HxC Floppy Emulator file operations."""

def rtzx(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert tape files to/from TZX format."""

def img2cpc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert images to Amstrad CPC format."""

def imgconverter(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert images to Amstrad CPC format."""

def cpc2img(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert Amstrad CPC images to standard formats."""

def martine(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert images using Martine."""

def grafx2(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Open/edit images in GrafX2."""

def grafx(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Open/edit images in GrafX2."""

def convgeneric(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Generic image conversion."""

def hideur(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """HiDeur image compression."""

def at3(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Play or convert Arkos Tracker files."""

def ArkosTracker3(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Play or convert Arkos Tracker files."""

def ayt(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Process AY sound files."""

def chipnsfx(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """ChipNSFX sound effects."""

def hspcompiler(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """HSP compiler for music."""

def hspc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """HSP compiler for music."""

def miny(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Minimise AY music files."""

def fap(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert AY music to FAP format."""

def SongToAkm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Convert song to AKM format."""

def cp(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Copy files."""

def copy(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Copy files."""

def mv(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Move or rename files."""

def move(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Move or rename files."""

def rename(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Move or rename files."""

def rm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Remove files."""

def mkdir(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create directory."""

def archive(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or extract archives."""

def arc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or extract archives."""

def echo(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Print a message."""

def print(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Print a message."""

def asmfmt(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Format Z80 assembly source code (basm-fmt)."""

def basm_fmt(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Format Z80 assembly source code (basm-fmt)."""

def basmopt(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Detect (and optionally fix) suboptimal Z80 instruction sequences."""

def extern(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run external command."""

def xfer(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Transfer files to real hardware (CPC WiFi, M4)."""

def cpcwifi(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Transfer files to real hardware (CPC WiFi, M4)."""

def m4(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Transfer files to real hardware (CPC WiFi, M4)."""

def cpr(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Create or modify CPR cartridge files."""

def csl(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Process CSL files."""

def bndbuild(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run another bndbuild project."""

def build(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Run another bndbuild project."""

def locomotive(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Process Locomotive BASIC files."""

def basic(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Process Locomotive BASIC files."""

def cpc(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Control emulator remotely."""

def emu(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Control emulator remotely."""

def emuctrl(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Control emulator remotely."""

def emucontrol(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Control emulator remotely."""

def Z80Profiler(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Profile and analyze Z80 code execution."""

def fade(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `fade`."""

def crunch(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `crunch`."""

def compress(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `compress`."""

def SongToAkg(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToAkg`."""

def SongToAky(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToAky`."""

def SongToEvents(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToEvents`."""

def SongToRaw(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToRaw`."""

def SongToSoundEffects(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToSoundEffects`."""

def SongToVgm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToVgm`."""

def SongToWav(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToWav`."""

def SongToYm(
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None:
    """Runs `SongToYm`."""
