class M4:
    def __init__(self, hostname: str) -> None: ...
    @property
    def hostname(self) -> str: ...
    def reset_m4(self) -> None: ...
    def reset_cpc(self) -> None: ...
    def run(self, path: str) -> None: ...
    def rm(self, path: str) -> None: ...
    def upload(
        self,
        path: str,
        remote_dir: str = "/tmp",
        header: tuple[str, int, int] | None = None,
    ) -> None: ...
    def upload_and_run(
        self, path: str, header: tuple[str, int, int] | None = None
    ) -> None: ...
    def pwd(self) -> str: ...
    def cd(self, directory: str) -> None: ...
    def ls(self) -> list[str]: ...
