[package]

name = "cpclib-z80emu"
version = "0.6.1-alpha.2"
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-asm = "0.6.1-alpha.2"
cpclib-sna = "0.6.1-alpha.2"
cpclib-common = "0.6.1-alpha.2"


cfg-if = "1.0.0"
delegate = "0.6.2"
either = "1.6.1"
failure = "0.1.8"
#memchr = "2.4.0"

paste = "1.0.7"
