[package]

name = "cpclib-z80emu"
version = "0.9.0"
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-asm.workspace = true
cpclib-sna.workspace = true
cpclib-common.workspace = true


cfg-if.workspace = true
delegate.workspace = true
either.workspace = true
paste.workspace = true
