[package]

name = "cpclib-z80emu"
version = "0.6.1-alpha.2"
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-asm = {version="0.6.1-alpha.2", default-features=false}
cpclib-sna = {version="0.6.1-alpha.2", default-features=false}
cpclib-common = {version="0.6.1-alpha.2", default-features=false}


cfg-if.workspace = true
delegate.workspace = true
either.workspace = true
failure.workspace = true
paste.workspace = true
