[package]

name = "cpclib-z80emu"
version = "0.4.4"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
cpclib-asm = "0.4.4"
cpclib-sna = "0.4.4"


bitsets = "0.1.1"
cfg-if = "1.0.0"
delegate = "0.5.0"
either = "1.6.1"
failure = "0.1.8"
itertools= "0.9.0"
memchr = "2.3.4"
nom = "6.0.0"
num_enum = "0.5.1"
num= "0.3.1"
paste = "1.0.3"
smallvec = "1.5.0"
strsim = "0.10.0"
