[package]

name = "cpclib-z80emu"
version = "0.5.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
cpclib-asm = "0.5.0"
cpclib-sna = "0.5.0"
cpclib-common = "0.5.0"


cfg-if = "1.0.0"
delegate = "0.5.2"
either = "1.6.1"
failure = "0.1.8"
#memchr = "2.4.0"

paste = "1.0.5"
