[package]

name = "cpclib-z80emu"
version = "0.4.2-alpha"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
cpclib-asm = "0.4.2-alpha"
cpclib-sna = "0.4.2-alpha"


bitsets = "0.1.1"
cfg-if = "0.1.10"
delegate = "0.4.3"
either = "1.6.1"
failure = "0.1.8"
itertools= "0.9.0"
memchr = "2.3.3"
nom = "5.1.2"
num_enum = "0.5.1"
num= "0.3.0"
paste = "1.0.1"
smallvec = "1.4.2"
strsim = "0.10.0"
