[package]
name = "cpclib-basm"
version = "0.6.0"
edition = "2021"
description = "z80 assembler relying on cpclib-asm"
repository = "https://github.com/cpcsdk/rust.cpclib"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-asm = { version = "0.6.0", features = ["basm"] }
cpclib-common = "0.6.0"
time = "0.3.9"

[dev-dependencies]
test-generator = "0.3.0"
tempfile = "3.3.0"
pretty_assertions = "1.2.1"
criterion = "0.3.5"
globset = "0.4.8"
regex = "1.5.5"
serial_test = "0.6.0"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }


[[bench]]
name = "basm_benchs"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1

[rust]
debuginfo-level = 1


[[bin]]
name = "basm"
path = "src/main.rs"
