[package]
name = "cpclib-wasm"
version.workspace = true
description = "webasm tools for cpclib"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cpclib-asm.workspace = true
cpclib-sna.workspace = true
cpclib-basic.workspace = true

wasm-bindgen.workspace = true


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { workspace = true, optional = true }


js-sys.workspace = true

web-sys = { workspace = true, features = [
  'console',
  'Blob', 'BlobPropertyBag',
  'Window', 'Document',
  'HtmlAnchorElement', 'Url',
] }


[dev-dependencies]
wasm-bindgen-test.workspace = true


