[package]
name = "cpclib-wasm"
version = "0.4.0"
description = "webasm tools for cpclib"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cpclib-asm.workspace = true
cpclib-sna.workspace = true
cpclib-basic.workspace = true

wasm-bindgen = "0.2.100" 


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }


js-sys = "0.3.77" 

[dependencies.web-sys]
version = "0.3.77"
features = [
  'console',
  'Blob', 'BlobPropertyBag',
  'Window', 'Document', 
  'HtmlAnchorElement', 'Url',

]


[dev-dependencies]
wasm-bindgen-test = "0.3.50"


