[package]
name = "cpclib-wasm"
version = "0.2.1-alpha.2"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
description = "webasm tools for cpclib"
repository = "https://github.com/cpcsdk/rust.cpclib"
license = "MIT"

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.80"
cpclib-asm = "0.6.0"
cpclib-sna = "0.6.0"
cpclib-basic = "0.6.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = "0.4.5"

js-sys = "0.3.57"

[dependencies.web-sys]
version = "0.3.57"
features = [
  'console',
  'Blob', 'BlobPropertyBag',
  'Window', 'Document', 
  'HtmlAnchorElement', 'Url',

]


[dev-dependencies]
wasm-bindgen-test = "0.3.30"

[profile.release]
debug = true
# Tell `rustc` to optimize for small code size.
#opt-level = "s"


