[package]
name = "cpclib-wasm"
version = "0.2.1-alpha.2"
description = "webasm tools for cpclib"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cpclib-asm.workspace = true
cpclib-sna.workspace = true
cpclib-basic.workspace = true

wasm-bindgen = "0.2.84" 


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = "0.4.5"

js-sys = "0.3.61" 

[dependencies.web-sys]
version = "0.3.61"
features = [
  'console',
  'Blob', 'BlobPropertyBag',
  'Window', 'Document', 
  'HtmlAnchorElement', 'Url',

]


[dev-dependencies]
wasm-bindgen-test = "0.3.34"



