;*** generated clipping (simple) ***
.clipping15 ld l,e : ld b,14 : : .id40shortD57 :   rst #08 : ld b,5 : .id40shortW7 : jp clipwidth7
.clipping16 .clipping17 .clipping18 ld l,e : ld b,15 : : .id40shortD67 :   rst #08 : ld b,6 : jr .id40shortW7
.clipping24 .clipping23 ld l,e : ld b,18 : : .id40shortD911 :   rst #08 : ld b,9 : .id40shortW11 : jp clipwidth11
.clipping22 ld l,e : ld b,18 : : jr .id40shortD911
.clipping10 .clipping11 ld l,e : ld b,13 : : .id40shortD77 :   rst #08 : ld b,7 : jr .id40shortW7
.clipping5 ld a,-4 : ld b,12 : : .id40shortC911 : rst #30 : ld b,9 : : jr .id40shortW11
.clipping6 ld l,e : ld b,12 : : .id40shortD87 :   rst #08 : ld b,8 : jr .id40shortW7
.clipping8 .clipping9 ld l,e : ld b,13 : : jr .id40shortD87
.clipping2 ld a,-4 : ld b,11 : : jr .id40shortC911
.clipping1 ld l,e : ld b,11 : : .id40shortD97 :   rst #08 : ld b,9 : jr .id40shortW7
.clipping7 ld l,e : ld b,13 : : jr .id40shortD97
.clipping14 ld l,e : ld b,14 : : .id40shortD511 :   rst #08 : ld b,5 : jr .id40shortW11
.clipping19 ld l,e : ld b,15 : : .id40shortD611 :   rst #08 : ld b,6 : jr .id40shortW11
.clipping20 ld l,e : ld b,16 : : .id40shortD711 :   rst #08 : ld b,7 : jr .id40shortW11
.clipping3 .clipping4 ld a,-4 : ld b,11 : : .id40shortC811 : rst #10 : : jr .id40shortW11
.clipping21 ld l,e : ld b,17 : : .id40shortD811 :   rst #08 : ld b,8 : jr .id40shortW11
.clipping12 .clipping13 ld l,e : ld b,14 : : jr .id40shortD811
