;*** generated clipping (simple) ***
.clipping6 .clipping5 ld l,e : rst #20 :  jp clipwidth7sub
.clipping11 ld l,e : rst #18 :  jp clipwidth15sub
.clipping14 .clipping15 .clipping16 ld a,8 : ld b,a : .id70shortL7 :  jp clipwidth7subadde
.clipping13 ld a,4 : .id70shortB8L11 : rst #20 : .id70shortL11 :  jp clipwidth11subadde
.clipping10 .clipping7 .clipping8 ld l,e : rst #20 :  jp clipwidth11sub
.clipping12 ld a,4 : .id70shortB7L11 : rst #18 : jr .id70shortL11
.clipping4 ld a,-4 : jr .id70shortB8L11
.clipping9 ld l,e : rst #20 :  jp clipwidth11sub
