;*** generated clipping (simple) ***
.clipping12 ld a,4 : .id67shortB7L3 : rst #18 : .id67shortL3 :  jp clipwidth3subadde
.clipping10 .clipping11 ld l,e : rst #18 : : .id67shortD67 :   rst #00 : .id67shortW7 : jp clipwidth7
.clipping4 ld a,-4 : .id67shortB8L11 : rst #20 : .id67shortL11 :  jp clipwidth11subadde
.clipping7 .clipping8 .clipping9 ld l,e : rst #20 :  jp clipwidth7sub
.clipping6 .clipping5 ld l,e : rst #20 :  jp clipwidth7sub
