;*** generated clipping (simple) ***
.clipping1 .clipping2 .clipping3 .clipping4 .clipping5 .clipping6 ld a,-4 : .id15shortB8L7 : rst #20 : .id15shortL7 :  jp clipwidth7subadde
.clipping22 .clipping21 .clipping20 ld l,e : rst #20 :  jp clipwidth11sub
.clipping8 .clipping7 .clipping10 .clipping9 ld a,-4 : .id15shortB8L11 : rst #20 : .id15shortL11 :  jp clipwidth11subadde
.clipping24 .clipping23 ld a,4 : jr .id15shortB8L7
.clipping18 .clipping19 .clipping11 .clipping12 .clipping13 ld l,e : rst #20 :  jp clipwidth7sub
.clipping17 .clipping16 .clipping15 ld l,e : rst #20 :  jp clipwidth7sub
.clipping14 ld l,e : rst #20 :  jp clipwidth7sub
