;*** generated clipping (simple) ***
.clipping11 .clipping23 .clipping12 .clipping24 .clipping1 .clipping13 .clipping2 .clipping14 .clipping3 .clipping15 .clipping4 .clipping16 .clipping5 ld a,-4 : .id13shortB8L11 : rst #20 : .id13shortL11 :  jp clipwidth11subadde
.clipping22 .clipping10 .clipping21 .clipping9 .clipping20 .clipping8 ld a,-4 : jr .id13shortB8L11
.clipping17 .clipping6 .clipping18 ld a,-4 : jr .id13shortB8L11
.clipping19 .clipping7 ld a,-4 : jr .id13shortB8L11
