;*** generated clipping (simple) ***
.clipping4 ld a,-4 : .id9shortB7L11 : rst #18 : .id9shortL11 :  jp clipwidth11subadde
.clipping5 .clipping6 .clipping7 .clipping8 .clipping9 .clipping10 ld a,-4 : .id9shortB8L11 : rst #20 : jr .id9shortL11
.clipping1 .clipping2 ld a,-8 : .id9shortB8L15 : rst #20 : .id9shortL15 :  jp clipwidth15subadde
.clipping11 ld a,-4 : jr .id9shortB8L11
.clipping3 ld a,-8 : .id9shortB7L15 : rst #18 : jr .id9shortL15
