;*** generated clipping (simple) ***
.clipping12 ld a,-4 : .id25shortB7L7 : rst #18 : .id25shortL7 :  jp clipwidth7subadde
.clipping14 ld a,-4 : ld b,9 : : .id25shortC77 : rst #30 : rst #18 : : .id25shortW7 : jp clipwidth7
.clipping13 ld a,-4 : .id25shortB9L7 : ld b,9 : jr .id25shortL7
.clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : .id25shortB6L11 : ld b,6 : .id25shortL11 :  jp clipwidth11subadde
.clipping4 .clipping3 .clipping2 ld a,-4 : .id25shortB8L11 : rst #20 : jr .id25shortL11
.clipping1 ld a,-4 : jr .id25shortB8L11
.clipping7 .clipping5 ld a,-4 : .id25shortB7L11 : rst #18 : jr .id25shortL11
.clipping6 ld a,-4 : jr .id25shortB7L11
