;*** generated clipping (simple) ***
.clipping10 ld l,e : ld b,14 : : .id45shortD57 :   rst #08 : ld b,5 : .id45shortW7 : jp clipwidth7
.clipping8 .clipping9 ld l,e : ld b,15 : : .id45shortD67 :   rst #08 : ld b,6 : jr .id45shortW7
.clipping3 .clipping2 ld l,e : ld b,18 : : .id45shortD911 :   rst #08 : ld b,9 : .id45shortW11 : jp clipwidth11
.clipping11 ld l,e : ld b,14 : : .id45shortD511 :   rst #08 : ld b,5 : jr .id45shortW11
.clipping6 .clipping7 ld l,e : ld b,15 : : .id45shortD611 :   rst #08 : ld b,6 : jr .id45shortW11
.clipping1 ld l,e : ld b,18 : : .id45shortD811 :   rst #08 : ld b,8 : jr .id45shortW11
.clipping5 ld l,e : ld b,16 : : jr .id45shortD611
.clipping4 ld l,e : ld b,17 : : .id45shortD711 :   rst #08 : ld b,7 : jr .id45shortW11
