;*** generated clipping (simple) ***
.clipping9 .clipping21 .clipping10 .clipping22 .clipping11 .clipping23 .clipping12 .clipping24 .clipping1 .clipping13 .clipping25 .clipping2 .clipping14 .clipping26 .clipping3 .clipping15 ld a,-4 : ld b,11 : : .id27shortC27 : rst #30 : ld b,2 : : .id27shortW7 : jp clipwidth7
.clipping20 .clipping8 .clipping31 .clipping19 .clipping7 .clipping30 .clipping18 .clipping6 ld a,-4 : ld b,11 : : jr .id27shortC27
.clipping27 .clipping4 .clipping16 .clipping28 ld a,-4 : ld b,11 : : jr .id27shortC27
.clipping29 .clipping17 ld a,-4 : ld b,11 : : jr .id27shortC27
.clipping5 ld a,-4 : ld b,11 : : jr .id27shortC27
