;*** generated clipping (simple) ***
.clipping12 ld l,e : rst #18 :  jp clipwidth7sub
.clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : .id34shortB6L11 : ld b,6 : .id34shortL11 :  jp clipwidth11subadde
.clipping1 .clipping4 .clipping3 ld a,-4 : .id34shortB8L11 : rst #20 : jr .id34shortL11
.clipping2 ld a,-4 : jr .id34shortB8L11
.clipping7 .clipping5 ld a,-4 : .id34shortB7L11 : rst #18 : jr .id34shortL11
.clipping6 ld a,-4 : jr .id34shortB7L11
