;*** generated clipping (simple) ***
.clipping15 ld l,e : rst #18 :  jp clipwidth7sub
.clipping34 ld a,12 : .id19shortB8L7 : rst #20 : .id19shortL7 :  jp clipwidth7subadde
.clipping8 .clipping9 .clipping10 .clipping11 .clipping12 .clipping13 .clipping14 .clipping6 .clipping7 ld a,-4 : .id19shortB7L11 : rst #18 : .id19shortL11 :  jp clipwidth11subadde
.clipping21 ld a,4 : ld b,9 :  rst #28 : .id19shortW15 : jp clipwidth15
.clipping22 ld a,4 : .id19shortB8L15 : rst #20 : .id19shortL15 :  jp clipwidth15subadde
.clipping19 .clipping18 .clipping17 .clipping20 ld l,e : rst #20 :  jp clipwidth15sub
.clipping28 .clipping39 .clipping27 .clipping31 .clipping29 .clipping32 .clipping33 .clipping35 ld a,12 : .id19shortB8L11 : rst #20 : jr .id19shortL11
.clipping38 .clipping26 .clipping37 .clipping25 ld a,12 : jr .id19shortB8L11
.clipping24 .clipping36 ld a,12 : jr .id19shortB8L11
.clipping16 ld l,e : rst #20 :  jp clipwidth11sub
.clipping23 ld a,8 : ld b,a : jr .id19shortL11
.clipping30 ld a,12 : jr .id19shortB7L11
.clipping1 .clipping2 .clipping3 ld a,-4 : jr .id19shortB8L11
.clipping5 .clipping4 ld a,-4 : jr .id19shortB8L11
