;*** generated clipping (simple) ***
.clipping15 ld a,-4 : .id51shortB7L7 : rst #18 : .id51shortL7 :  jp clipwidth7subadde
.clipping5 ld a,-4 : .id51shortB8L7 : rst #20 : jr .id51shortL7
.clipping11 .clipping12 .clipping13 .clipping14 ld a,-4 : .id51shortB6L11 : ld b,6 : .id51shortL11 :  jp clipwidth11subadde
.clipping6 ld a,-8 : .id51shortB8L15 : rst #20 : .id51shortL15 :  jp clipwidth15subadde
.clipping7 ld a,-8 : .id51shortB7L15 : rst #18 : jr .id51shortL15
.clipping19 .clipping16 .clipping17 ld a,-4 : .id51shortB8L11 : rst #20 : jr .id51shortL11
.clipping8 .clipping9 .clipping10 ld a,-4 : .id51shortB7L11 : rst #18 : jr .id51shortL11
.clipping18 ld a,-4 : jr .id51shortB8L11
