;*** generated clipping (simple) ***
.clipping13 ld a,-4 : .id24shortB9L7 : ld b,9 : .id24shortL7 :  jp clipwidth7subadde
.clipping14 .clipping15 .clipping18 .clipping19 ld a,-4 : ld b,11 : : .id24shortC97 : rst #30 : ld b,9 : : .id24shortW7 : jp clipwidth7
.clipping17 .clipping16 ld a,-4 : ld b,11 : : .id24shortC911 : rst #30 : ld b,9 : : .id24shortW11 : jp clipwidth11
.clipping20 ld a,-4 : ld b,11 : : jr .id24shortC97
