;*** generated clipping (simple) ***
.clipping12 ld l,e : rst #18 :  jp clipwidth7sub
.clipping14 ld l,e : ld b,9 : : .id36shortD77 :   rst #08 : ld b,7 : .id36shortW7 : jp clipwidth7
.clipping13 ld l,e : ld b,9 :  jp clipwidth7sub
.clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : .id36shortB6L11 : ld b,6 : .id36shortL11 :  jp clipwidth11subadde
.clipping4 .clipping3 .clipping2 ld a,-4 : .id36shortB8L11 : rst #20 : jr .id36shortL11
.clipping1 ld a,-4 : jr .id36shortB8L11
.clipping5 .clipping6 ld a,-4 : .id36shortB7L11 : rst #18 : jr .id36shortL11
.clipping7 ld a,-4 : jr .id36shortB7L11
