;*** generated clipping (simple) ***
.clipping7 .clipping19 .clipping8 .clipping20 .clipping9 .clipping10 .clipping11 .clipping12 .clipping1 .clipping13 .clipping2 ld l,e : rst #20 :  jp clipwidth7sub
.clipping18 .clipping6 .clipping17 .clipping5 .clipping16 ld l,e : rst #20 :  jp clipwidth7sub
.clipping14 .clipping3 .clipping15 ld l,e : rst #20 :  jp clipwidth7sub
.clipping4 ld l,e : rst #20 :  jp clipwidth7sub
