;*** generated clipping (simple) ***
.clipping7 .clipping8 .clipping9 .clipping10 ld l,e : rst #20 :  jp clipwidth7sub
.clipping12 .clipping11 .clipping14 ld l,e : rst #20 :  jp clipwidth11sub
.clipping13 ld l,e : rst #20 :  jp clipwidth11sub
.clipping6 .clipping1 .clipping2 .clipping3 ld a,-4 : .id0shortB8L11 : rst #20 : .id0shortL11 :  jp clipwidth11subadde
.clipping5 .clipping4 ld a,-4 : jr .id0shortB8L11
