;*** generated clipping (simple) ***
.clipping8 ld l,e : rst #20 :  jp clipwidth7sub
.clipping9 .clipping21 .clipping10 .clipping22 .clipping11 .clipping23 .clipping12 .clipping24 .clipping1 .clipping13 .clipping2 .clipping14 ld a,-4 : .id3shortB8L11 : rst #20 : .id3shortL11 :  jp clipwidth11subadde
.clipping20 .clipping19 .clipping7 .clipping18 .clipping6 .clipping17 ld a,-4 : jr .id3shortB8L11
.clipping3 .clipping15 .clipping4 ld a,-4 : jr .id3shortB8L11
.clipping5 .clipping16 ld a,-4 : jr .id3shortB8L11
