;*** generated clipping (simple) ***
.clipping15 .clipping4 .clipping5 .clipping6 .clipping13 .clipping14 ld l,e : rst #20 :  jp clipwidth3sub
.clipping2 .clipping1 .clipping12 .clipping11 .clipping10 .clipping3 .clipping16 .clipping17 ld a,-4 : .id62shortB8L7 : rst #20 : .id62shortL7 :  jp clipwidth7subadde
.clipping9 .clipping20 .clipping8 .clipping19 ld a,-4 : jr .id62shortB8L7
.clipping18 .clipping7 ld a,-4 : jr .id62shortB8L7
