;*** generated clipping (simple) ***
.clipping15 ld a,-4 : .id18shortB7L7 : rst #18 : .id18shortL7 :  jp clipwidth7subadde
.clipping11 .clipping12 .clipping13 .clipping14 .clipping6 .clipping7 .clipping8 .clipping9 .clipping10 ld a,-4 : .id18shortB7L11 : rst #18 : .id18shortL11 :  jp clipwidth11subadde
.clipping33 .clipping32 .clipping31 .clipping29 .clipping28 .clipping39 .clipping27 .clipping38 ld a,-20 : .id18shortB8L23 : rst #20 : .id18shortL23 :  jp clipwidth23subadde
.clipping26 .clipping37 .clipping25 .clipping36 .clipping24 .clipping35 ld a,-20 : jr .id18shortB8L23
.clipping21 ld a,-16 : ld b,9 :  rst #28 : .id18shortW19 : jp clipwidth19
.clipping34 .clipping22 .clipping23 ld a,-16 : .id18shortB8L19 : rst #20 : .id18shortL19 :  jp clipwidth19subadde
.clipping19 .clipping18 .clipping20 ld a,-12 : .id18shortB8L15 : rst #20 : .id18shortL15 :  jp clipwidth15subadde
.clipping17 ld a,-12 : jr .id18shortB8L15
.clipping5 .clipping1 .clipping2 ld a,-4 : .id18shortB8L11 : rst #20 : jr .id18shortL11
.clipping30 ld a,-20 : .id18shortB7L23 : rst #18 : jr .id18shortL23
.clipping16 ld a,-8 : jr .id18shortB8L11
.clipping4 .clipping3 ld a,-4 : jr .id18shortB8L11
