;*** generated clipping (simple) ***
.clipping15 ld l,e : rst #18 :  jp clipwidth7sub
.clipping5 ld l,e : rst #20 :  jp clipwidth7sub
.clipping11 .clipping12 .clipping13 .clipping14 ld a,-4 : .id44shortB6L11 : ld b,6 : .id44shortL11 :  jp clipwidth11subadde
.clipping6 ld a,-4 : .id44shortB8L15 : rst #20 : .id44shortL15 :  jp clipwidth15subadde
.clipping7 ld a,-4 : .id44shortB7L15 : rst #18 : jr .id44shortL15
.clipping19 .clipping16 .clipping17 ld a,-4 : .id44shortB8L11 : rst #20 : jr .id44shortL11
.clipping8 .clipping9 .clipping10 ld a,-4 : .id44shortB7L11 : rst #18 : jr .id44shortL11
.clipping18 ld a,-4 : jr .id44shortB8L11
