;*** generated clipping (simple) ***
.clipping24 ld a,-4 : ld b,11 : : .id55shortC27 : rst #30 : ld b,2 : : .id55shortW7 : jp clipwidth7
.clipping19 ld a,-4 : ld b,12 : : .id55shortC37 : rst #30 : ld b,3 : : jr .id55shortW7
.clipping14 .clipping15 .clipping16 .clipping17 .clipping18 ld a,-4 : ld b,13 : : .id55shortC47 : rst #30 : ld b,4 : : jr .id55shortW7
.clipping13 .clipping12 ld a,-8 : ld b,14 : : .id55shortC511 : rst #30 : ld b,5 : : .id55shortW11 : jp clipwidth11
.clipping22 .clipping23 ld a,-4 : ld b,11 : : .id55shortC211 : rst #30 : ld b,2 : : jr .id55shortW11
.clipping20 ld a,-4 : ld b,12 : : .id55shortC311 : rst #30 : ld b,3 : : jr .id55shortW11
.clipping21 ld a,-4 : ld b,11 : : jr .id55shortC211
