;*** generated clipping (simple) ***
.clipping1 ld l,e : ld b,11 : : .id41shortD27 :   rst #08 : ld b,2 : .id41shortW7 : jp clipwidth7
.clipping6 ld l,e : ld b,12 : : .id41shortD37 :   rst #08 : ld b,3 : jr .id41shortW7
.clipping8 .clipping9 .clipping10 .clipping11 .clipping7 ld l,e : ld b,13 : : .id41shortD47 :   rst #08 : ld b,4 : jr .id41shortW7
.clipping13 .clipping12 ld l,e : ld b,14 : : .id41shortD511 :   rst #08 : ld b,5 : .id41shortW11 : jp clipwidth11
.clipping3 .clipping4 ld a,-4 : ld b,11 : : .id41shortC211 : rst #30 : ld b,2 : : jr .id41shortW11
.clipping5 ld a,-4 : ld b,12 : : .id41shortC311 : rst #30 : ld b,3 : : jr .id41shortW11
.clipping2 ld a,-4 : ld b,11 : : jr .id41shortC211
