[package]
name = "snapshot"
version = "0.1.0-alpha1"
authors = ["Krusty/Benediction"]
build = "build.rs"

[build-dependencies]
built = "0.3.0"

[dependencies]
built = "0.3.0"
time = "0.1.40"
semver = "0.9.0"
clap = "*"
cpc = { path = "../cpclib" }
