#!/usr/bin/env python3
"""Regenerates python/cpclib_python/tools.pyi from the installed extension's
`tools.commands()`. Run it after bndbuild gains or loses a tool (a test checks
the stub covers every tool): `python dev/gen_tools_stub.py`."""
import keyword
from pathlib import Path

from cpclib_python import tools

HEAD = '''# Generated by dev/gen_tools_stub.py from `tools.commands()`: one function per
# tool (and per alias that is a valid Python name). Tools such as `2cdt` are
# reached with `run("2cdt", ...)`.
from typing import Any

from ._types import OutputCallback

def commands() -> list[dict[str, Any]]: ...
def run(
    command: str,
    *args: str,
    on_output: OutputCallback | None = None,
    capture: bool = False,
) -> dict[str, str] | None: ...

'''

seen: set[str] = set()
functions = []
for entry in tools.commands():
    for name in (entry["name"], *entry["aliases"]):
        ident = name.replace("-", "_")
        if not ident.isidentifier() or keyword.iskeyword(ident) or ident in seen:
            continue
        seen.add(ident)
        doc = (entry["description"] or f"Runs `{name}`").replace("\n", " ").replace('"""', "'")
        functions.append(
            f"def {ident}(\n    *args: str,\n    on_output: OutputCallback | None = None,\n"
            f"    capture: bool = False,\n) -> dict[str, str] | None:\n    \"\"\"{doc}.\"\"\"\n"
        )

target = Path(__file__).resolve().parents[1] / "python" / "cpclib_python" / "tools.pyi"
target.write_text(HEAD + "\n".join(functions))
print(f"{len(functions)} tools written to {target}")
