;*** generated clipping (simple) ***
.clipping5 ld a,-4 : .id8shortB7L11 : rst #18 : .id8shortL11 :  jp clipwidth11subadde
.clipping6 .clipping7 .clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : .id8shortB8L11 : rst #20 : jr .id8shortL11
.clipping2 .clipping1 ld a,-4 : .id8shortB8L15 : rst #20 : .id8shortL15 :  jp clipwidth15subadde
.clipping3 .clipping4 ld a,-4 : .id8shortB7L15 : rst #18 : jr .id8shortL15
