;*** generated clipping (simple) ***
.clipping1 ld a,-4 : ld b,11 : : .id30shortC27 : rst #30 : ld b,2 : : .id30shortW7 : jp clipwidth7
.clipping6 ld a,-4 : ld b,12 : : .id30shortC37 : rst #30 : ld b,3 : : jr .id30shortW7
.clipping7 .clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : ld b,13 : : .id30shortC47 : rst #30 : ld b,4 : : jr .id30shortW7
.clipping13 .clipping12 ld a,-8 : ld b,14 : : .id30shortC511 : rst #30 : ld b,5 : : .id30shortW11 : jp clipwidth11
.clipping3 .clipping4 ld a,-4 : ld b,11 : : .id30shortC211 : rst #30 : ld b,2 : : jr .id30shortW11
.clipping5 ld a,-4 : ld b,12 : : .id30shortC311 : rst #30 : ld b,3 : : jr .id30shortW11
.clipping2 ld a,-4 : ld b,11 : : jr .id30shortC211
