;*** generated clipping (simple) ***
.clipping10 .clipping22 .clipping11 .clipping23 .clipping12 .clipping24 .clipping1 .clipping13 .clipping25 .clipping2 .clipping14 .clipping26 .clipping3 .clipping15 .clipping27 .clipping4 ld l,e : ld b,11 : : .id38shortD27 :   rst #08 : ld b,2 : .id38shortW7 : jp clipwidth7
.clipping21 .clipping9 .clipping20 .clipping8 .clipping31 .clipping19 .clipping7 .clipping30 ld l,e : ld b,11 : : jr .id38shortD27
.clipping16 .clipping28 .clipping5 .clipping17 ld l,e : ld b,11 : : jr .id38shortD27
.clipping18 .clipping6 ld l,e : ld b,11 : : jr .id38shortD27
.clipping29 ld l,e : ld b,11 : : jr .id38shortD27
