;*** generated clipping (simple) ***
.clipping7 .clipping19 .clipping8 .clipping20 .clipping9 .clipping10 .clipping11 .clipping12 .clipping1 .clipping13 .clipping2 ld a,-4 : .id63shortB8L7 : rst #20 : .id63shortL7 :  jp clipwidth7subadde
.clipping18 .clipping6 .clipping17 .clipping5 .clipping16 ld a,-4 : jr .id63shortB8L7
.clipping14 .clipping3 .clipping15 ld a,-4 : jr .id63shortB8L7
.clipping4 ld a,-4 : jr .id63shortB8L7
