;*** generated clipping (simple) ***
.clipping12 ld a,-4 : .id23shortB7L7 : rst #18 : .id23shortL7 :  jp clipwidth7subadde
.clipping8 .clipping9 .clipping10 .clipping11 ld a,-4 : .id23shortB6L11 : ld b,6 : .id23shortL11 :  jp clipwidth11subadde
.clipping4 .clipping3 .clipping2 ld a,-4 : .id23shortB8L11 : rst #20 : jr .id23shortL11
.clipping1 ld a,-4 : jr .id23shortB8L11
.clipping7 .clipping5 ld a,-4 : .id23shortB7L11 : rst #18 : jr .id23shortL11
.clipping6 ld a,-4 : jr .id23shortB7L11
