;*** generated clipping (simple) ***
.clipping3 .clipping15 .clipping4 .clipping16 .clipping5 .clipping17 .clipping6 .clipping18 .clipping7 .clipping19 .clipping8 .clipping20 .clipping9 ld a,-4 : .id61shortB8L7 : rst #20 : .id61shortL7 :  jp clipwidth7subadde
.clipping14 .clipping2 .clipping13 .clipping1 .clipping24 .clipping12 ld a,-4 : jr .id61shortB8L7
.clipping21 .clipping10 .clipping22 ld a,-4 : jr .id61shortB8L7
.clipping23 .clipping11 ld a,-4 : jr .id61shortB8L7
