;*** generated clipping (simple) ***
.clipping16 ld a,8 : rst #18 :  rst #28 : .id68shortW3 : jp clipwidth3
.clipping15 ld a,8 : .id68shortB7L3 : rst #18 : .id68shortL3 :  jp clipwidth3subadde
.clipping14 ld a,8 : ld b,a : jr .id68shortL3
.clipping12 ld a,4 : .id68shortB7L7 : rst #18 : .id68shortL7 :  jp clipwidth7subadde
.clipping5 .clipping6 ld l,e : rst #20 :  jp clipwidth7sub
.clipping9 .clipping10 .clipping7 ld l,e : rst #20 :  jp clipwidth11sub
.clipping13 ld a,4 : .id68shortB8L7 : rst #20 : jr .id68shortL7
.clipping11 ld l,e : rst #18 :  jp clipwidth11sub
.clipping4 ld a,-4 : .id68shortB8L11 : rst #20 : .id68shortL11 :  jp clipwidth11subadde
.clipping8 ld l,e : rst #20 :  jp clipwidth11sub
