;*** generated clipping (simple) ***
.clipping3 .clipping15 .clipping27 .clipping4 .clipping16 .clipping28 .clipping5 .clipping17 .clipping29 .clipping6 .clipping18 .clipping30 .clipping7 .clipping19 .clipping31 .clipping8 ld l,e : ld b,11 : : .id39shortD97 :   rst #08 : ld b,9 : .id39shortW7 : jp clipwidth7
.clipping26 .clipping14 .clipping2 .clipping25 .clipping13 .clipping1 .clipping24 .clipping12 ld l,e : ld b,11 : : jr .id39shortD97
.clipping20 .clipping9 .clipping21 .clipping10 ld l,e : ld b,11 : : jr .id39shortD97
.clipping23 .clipping11 ld l,e : ld b,11 : : jr .id39shortD97
.clipping22 ld l,e : ld b,11 : : jr .id39shortD97
