;*** generated clipping (simple) ***
.clipping11 .clipping12 .clipping13 .clipping14 .clipping15 .clipping16 .clipping17 .clipping18 .clipping19 ld a,-4 : .id14shortB8L7 : rst #20 : .id14shortL7 :  jp clipwidth7subadde
.clipping10 .clipping9 .clipping8 .clipping7 ld a,-4 : .id14shortB8L11 : rst #20 : .id14shortL11 :  jp clipwidth11subadde
.clipping23 .clipping22 .clipping21 .clipping20 .clipping24 ld a,-8 : jr .id14shortB8L11
.clipping6 .clipping5 .clipping4 .clipping3 ld l,e : rst #20 :  jp clipwidth7sub
.clipping1 .clipping2 ld l,e : rst #20 :  jp clipwidth7sub
