;*** generated clipping (simple) ***
.clipping4 .clipping5 .clipping6 ld l,e : rst #20 :  jp clipwidth3sub
.clipping10 .clipping9 .clipping11 .clipping12 .clipping1 .clipping13 .clipping2 .clipping14 .clipping3 ld l,e : rst #20 :  jp clipwidth7sub
.clipping20 .clipping8 .clipping19 .clipping7 .clipping18 ld l,e : rst #20 :  jp clipwidth7sub
.clipping15 .clipping16 ld l,e : rst #20 :  jp clipwidth7sub
.clipping17 ld l,e : rst #20 :  jp clipwidth7sub
