;*** generated clipping (simple) ***
.clipping9 .clipping21 .clipping10 .clipping22 .clipping11 .clipping23 .clipping12 .clipping24 .clipping1 .clipping13 .clipping2 .clipping14 .clipping3 ld a,-4 : .id5shortB8L11 : rst #20 : .id5shortL11 :  jp clipwidth11subadde
.clipping20 .clipping8 .clipping19 .clipping7 .clipping18 .clipping6 ld a,-4 : jr .id5shortB8L11
.clipping15 .clipping4 .clipping16 ld a,-4 : jr .id5shortB8L11
.clipping17 .clipping5 ld a,-4 : jr .id5shortB8L11
