;*** generated clipping (simple) ***
.clipping2 .clipping14 .clipping26 .clipping3 .clipping15 .clipping27 .clipping4 .clipping16 .clipping28 .clipping5 .clipping17 .clipping29 .clipping6 .clipping18 .clipping30 .clipping7 ld a,-4 : ld b,11 : : .id28shortC97 : rst #30 : ld b,9 : : .id28shortW7 : jp clipwidth7
.clipping25 .clipping13 .clipping1 .clipping24 .clipping12 .clipping23 .clipping11 .clipping22 ld a,-4 : ld b,11 : : jr .id28shortC97
.clipping19 .clipping31 .clipping8 .clipping20 ld a,-4 : ld b,11 : : jr .id28shortC97
.clipping10 .clipping21 ld a,-4 : ld b,11 : : jr .id28shortC97
.clipping9 ld a,-4 : ld b,11 : : jr .id28shortC97
