;*** generated clipping (simple) ***
.clipping7 .clipping8 .clipping9 .clipping10 ld a,-4 : .id1shortB8L7 : rst #20 : .id1shortL7 :  jp clipwidth7subadde
.clipping6 .clipping5 .clipping4 .clipping1 ld a,-4 : .id1shortB8L11 : rst #20 : .id1shortL11 :  jp clipwidth11subadde
.clipping3 .clipping2 ld a,-4 : jr .id1shortB8L11
.clipping14 .clipping11 .clipping12 ld a,-8 : jr .id1shortB8L11
.clipping13 ld a,-8 : jr .id1shortB8L11
