;*** generated clipping (simple) ***
.clipping7 .clipping19 .clipping8 .clipping20 .clipping9 .clipping21 .clipping10 .clipping22 .clipping11 .clipping23 .clipping12 .clipping24 .clipping1 ld l,e : rst #20 :  jp clipwidth7sub
.clipping18 .clipping6 .clipping17 .clipping5 .clipping16 .clipping4 ld l,e : rst #20 :  jp clipwidth7sub
.clipping13 .clipping2 .clipping14 ld l,e : rst #20 :  jp clipwidth7sub
.clipping15 .clipping3 ld l,e : rst #20 :  jp clipwidth7sub
