;*** generated clipping (simple) ***
.clipping15 ld a,-4 : ld b,14 : : .id29shortC57 : rst #30 : ld b,5 : : .id29shortW7 : jp clipwidth7
.clipping16 .clipping17 .clipping18 ld a,-4 : ld b,15 : : .id29shortC67 : rst #30 : ld b,6 : : jr .id29shortW7
.clipping24 .clipping23 ld a,-8 : ld b,18 : : .id29shortC911 : rst #30 : ld b,9 : : .id29shortW11 : jp clipwidth11
.clipping22 ld a,-8 : ld b,18 : : jr .id29shortC911
.clipping10 .clipping11 ld a,-4 : ld b,13 : : .id29shortC77 : rst #30 : rst #18 : : jr .id29shortW7
.clipping5 ld a,-4 : ld b,12 : : jr .id29shortC911
.clipping6 ld a,-4 : ld b,12 : : .id29shortC87 : rst #10 : : jr .id29shortW7
.clipping8 .clipping9 ld a,-4 : ld b,13 : : jr .id29shortC87
.clipping2 ld a,-4 : ld b,11 : : jr .id29shortC911
.clipping1 ld a,-4 : ld b,11 : : .id29shortC97 : rst #30 : ld b,9 : : jr .id29shortW7
.clipping7 ld a,-4 : ld b,13 : : jr .id29shortC97
.clipping14 ld a,-8 : ld b,14 : : .id29shortC511 : rst #30 : ld b,5 : : jr .id29shortW11
.clipping19 ld a,-8 : ld b,15 : : .id29shortC611 : rst #30 : ld b,6 : : jr .id29shortW11
.clipping20 ld a,-8 : ld b,16 : : .id29shortC711 : rst #30 : rst #18 : : jr .id29shortW11
.clipping3 .clipping4 ld a,-4 : ld b,11 : : .id29shortC811 : rst #10 : : jr .id29shortW11
.clipping21 ld a,-8 : ld b,17 : : jr .id29shortC811
.clipping12 .clipping13 ld a,-8 : ld b,14 : : jr .id29shortC811
