;*** generated clipping (simple) ***
.clipping10 ld a,-4 : ld b,14 : : .id52shortC57 : rst #30 : ld b,5 : : .id52shortW7 : jp clipwidth7
.clipping8 .clipping9 ld a,-4 : ld b,15 : : .id52shortC67 : rst #30 : ld b,6 : : jr .id52shortW7
.clipping3 .clipping2 ld a,-8 : ld b,18 : : .id52shortC911 : rst #30 : ld b,9 : : .id52shortW11 : jp clipwidth11
.clipping11 ld a,-8 : ld b,14 : : .id52shortC511 : rst #30 : ld b,5 : : jr .id52shortW11
.clipping6 .clipping7 ld a,-8 : ld b,15 : : .id52shortC611 : rst #30 : ld b,6 : : jr .id52shortW11
.clipping1 ld a,-8 : ld b,18 : : .id52shortC811 : rst #10 : : jr .id52shortW11
.clipping5 ld a,-8 : ld b,16 : : jr .id52shortC611
.clipping4 ld a,-8 : ld b,17 : : .id52shortC711 : rst #30 : rst #18 : : jr .id52shortW11
