;*** generated clipping (simple) ***
.clipping10 ld l,e : ld b,14 : : .id47shortD57 :   rst #08 : ld b,5 : .id47shortW7 : jp clipwidth7
.clipping8 .clipping9 ld l,e : ld b,15 : : .id47shortD67 :   rst #08 : ld b,6 : jr .id47shortW7
.clipping3 .clipping2 ld l,e : ld b,18 : : .id47shortD911 :   rst #08 : ld b,9 : .id47shortW11 : jp clipwidth11
.clipping14 .clipping15 ld l,e : ld b,13 : : .id47shortD77 :   rst #08 : ld b,7 : jr .id47shortW7
.clipping20 ld a,-4 : ld b,12 : : .id47shortC911 : rst #30 : ld b,9 : : jr .id47shortW11
.clipping19 ld l,e : ld b,12 : : .id47shortD87 :   rst #08 : ld b,8 : jr .id47shortW7
.clipping16 .clipping17 ld l,e : ld b,13 : : jr .id47shortD87
.clipping23 ld a,-4 : ld b,11 : : jr .id47shortC911
.clipping24 ld l,e : ld b,11 : : .id47shortD97 :   rst #08 : ld b,9 : jr .id47shortW7
.clipping18 ld l,e : ld b,13 : : jr .id47shortD97
.clipping11 ld l,e : ld b,14 : : .id47shortD511 :   rst #08 : ld b,5 : jr .id47shortW11
.clipping12 ld l,e : ld b,14 : : .id47shortD611 :   rst #08 : ld b,6 : jr .id47shortW11
.clipping6 .clipping7 ld l,e : ld b,15 : : jr .id47shortD611
.clipping1 ld l,e : ld b,18 : : .id47shortD811 :   rst #08 : ld b,8 : jr .id47shortW11
.clipping5 ld l,e : ld b,16 : : jr .id47shortD611
.clipping4 ld l,e : ld b,17 : : .id47shortD711 :   rst #08 : ld b,7 : jr .id47shortW11
.clipping21 .clipping22 ld a,-4 : ld b,11 : : .id47shortC811 : rst #10 : : jr .id47shortW11
.clipping13 ld l,e : ld b,14 : : jr .id47shortD811
