;*** generated clipping (simple) ***
.clipping5 .clipping6 ld a,-4 : .id6shortB8L7 : rst #20 : .id6shortL7 :  jp clipwidth7subadde
.clipping16 .clipping15 ld a,-16 : .id6shortB8L19 : rst #20 : .id6shortL19 :  jp clipwidth19subadde
.clipping3 ld a,-4 : .id6shortB7L11 : rst #18 : .id6shortL11 :  jp clipwidth11subadde
.clipping9 .clipping10 .clipping7 .clipping8 ld a,-8 : .id6shortB8L11 : rst #20 : jr .id6shortL11
.clipping2 ld a,-4 : .id6shortB8L15 : rst #20 : .id6shortL15 :  jp clipwidth15subadde
.clipping14 .clipping13 ld a,-12 : jr .id6shortB8L15
.clipping12 .clipping11 ld a,-12 : .id6shortB7L15 : rst #18 : jr .id6shortL15
.clipping4 ld a,-4 : jr .id6shortB8L11
.clipping1 ld l,e : rst #20 :  jp clipwidth11sub
