;*** generated clipping (simple) ***
.clipping4 .clipping5 .clipping6 ld a,-4 : .id11shortB8L7 : rst #20 : .id11shortL7 :  jp clipwidth7subadde
.clipping18 .clipping17 .clipping7 .clipping19 .clipping8 .clipping20 .clipping9 .clipping10 .clipping11 ld a,-4 : .id11shortB8L11 : rst #20 : .id11shortL11 :  jp clipwidth11subadde
.clipping16 .clipping15 .clipping3 .clipping14 .clipping2 ld a,-4 : jr .id11shortB8L11
.clipping12 .clipping1 ld a,-4 : jr .id11shortB8L11
.clipping13 ld a,-4 : jr .id11shortB8L11
