;*** generated clipping (simple) ***
.clipping24 ld l,e : ld b,11 : : .id48shortD27 :   rst #08 : ld b,2 : .id48shortW7 : jp clipwidth7
.clipping19 ld l,e : ld b,12 : : .id48shortD37 :   rst #08 : ld b,3 : jr .id48shortW7
.clipping14 .clipping15 .clipping16 .clipping17 .clipping18 ld l,e : ld b,13 : : .id48shortD47 :   rst #08 : ld b,4 : jr .id48shortW7
.clipping13 .clipping12 ld l,e : ld b,14 : : .id48shortD511 :   rst #08 : ld b,5 : .id48shortW11 : jp clipwidth11
.clipping22 .clipping23 ld a,-4 : ld b,11 : : .id48shortC211 : rst #30 : ld b,2 : : jr .id48shortW11
.clipping20 ld a,-4 : ld b,12 : : .id48shortC311 : rst #30 : ld b,3 : : jr .id48shortW11
.clipping21 ld a,-4 : ld b,11 : : jr .id48shortC211
