;*** generated clipping (simple) ***
.clipping10 ld a,-4 : ld b,14 : : .id54shortC57 : rst #30 : ld b,5 : : .id54shortW7 : jp clipwidth7
.clipping8 .clipping9 ld a,-4 : ld b,15 : : .id54shortC67 : rst #30 : ld b,6 : : jr .id54shortW7
.clipping3 .clipping2 ld a,-8 : ld b,18 : : .id54shortC911 : rst #30 : ld b,9 : : .id54shortW11 : jp clipwidth11
.clipping14 .clipping15 ld a,-4 : ld b,13 : : .id54shortC77 : rst #30 : rst #18 : : jr .id54shortW7
.clipping20 ld a,-4 : ld b,12 : : jr .id54shortC911
.clipping19 ld a,-4 : ld b,12 : : .id54shortC87 : rst #10 : : jr .id54shortW7
.clipping16 .clipping17 ld a,-4 : ld b,13 : : jr .id54shortC87
.clipping23 ld a,-4 : ld b,11 : : jr .id54shortC911
.clipping24 ld a,-4 : ld b,11 : : .id54shortC97 : rst #30 : ld b,9 : : jr .id54shortW7
.clipping18 ld a,-4 : ld b,13 : : jr .id54shortC97
.clipping11 ld a,-8 : ld b,14 : : .id54shortC511 : rst #30 : ld b,5 : : jr .id54shortW11
.clipping12 ld a,-8 : ld b,14 : : .id54shortC611 : rst #30 : ld b,6 : : jr .id54shortW11
.clipping6 .clipping7 ld a,-8 : ld b,15 : : jr .id54shortC611
.clipping1 ld a,-8 : ld b,18 : : .id54shortC811 : rst #10 : : jr .id54shortW11
.clipping5 ld a,-8 : ld b,16 : : jr .id54shortC611
.clipping4 ld a,-8 : ld b,17 : : .id54shortC711 : rst #30 : rst #18 : : jr .id54shortW11
.clipping21 .clipping22 ld a,-4 : ld b,11 : : jr .id54shortC811
.clipping13 ld a,-8 : ld b,14 : : jr .id54shortC811
