;*** generated clipping (simple) ***
.clipping5 .clipping6 ld l,e : rst #20 :  jp clipwidth7sub
.clipping2 ld a,-8 : .id7shortB8L15 : rst #20 : .id7shortL15 :  jp clipwidth15subadde
.clipping14 ld a,8 : ld b,a : .id7shortL7 :  jp clipwidth7subadde
.clipping3 ld a,-4 : .id7shortB7L11 : rst #18 : .id7shortL11 :  jp clipwidth11subadde
.clipping12 ld a,4 : jr .id7shortB7L11
.clipping1 ld a,-8 : .id7shortB8L11 : rst #20 : jr .id7shortL11
.clipping4 ld a,-4 : jr .id7shortB8L11
.clipping7 .clipping8 .clipping9 .clipping10 ld l,e : rst #20 :  jp clipwidth11sub
.clipping11 ld l,e : rst #18 :  jp clipwidth15sub
.clipping16 .clipping15 ld a,8 : ld b,a : jr .id7shortL11
.clipping13 ld a,4 : jr .id7shortB8L11
