[package]
name = "cpc"
version = "0.1.3"
authors = ["Romain Giot <giot.romain@gmail.com"]
edition = "2018"

[dependencies]
num="0.1.42"
image = "*"
vecmath = "*"
matches = "*"
lazy_static= "*"
memchr = "*"
smallvec = "*"
itertools="0.7.8"

[dependencies.nom]
version = "4.0.0"
#features = ["verbose-errors"]
