[package]

name = "cpclib"
version = "0.6.1-alpha.2"
description = "Set of tools and libraries to ease demomaking on the Amstrad CPC platform. WIP"
keywords = ["amstrad", "demo", "z80", "dsk" ,"sna"]
categories = ["command-line-utilities", "development-tools", "emulators"]
readme = "Readme.mkd"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]

cpclib-basic = "0.6.1-alpha.2"
cpclib-sna = "0.6.1-alpha.2"


cpclib-asm = "0.6.1-alpha.2"
cpclib-z80emu = "0.6.1-alpha.2"
cpclib-xfer = "0.6.1-alpha.2"
cpclib-disc = "0.6.1-alpha.2"
cpclib-macros = "0.6.1-alpha.2"
cpclib-common = "0.6.1-alpha.2"
cpclib-image = "0.6.1-alpha.2"

anyhow = "1.0.57"
arrayref= "0.3.6"
cfg-if = "1.0.0"
custom_error = "1.9.2"
dbg = "1.0.4"
delegate = "0.6.2"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.2"

matches = "0.1.9"
#memchr = "2.4.0"
paste = "1.0.7"
serde = { version = "1.0.137", features = ["derive"] }
tempfile= "3.3.0"




path-absolutize = { version = "3.0.13", optional = true }
curl = { version = "0.4.43", optional = true }
reqwest = { version = "0.11.10", optional = true }

time = { version = "0.3.9", optional = true }



log = { version = "0.4.17", optional = true }




[dev-dependencies] 
pretty_assertions= "1.2.1"
tempfile = "3.3.0"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }


[features]
default = ["xferlib"]
xferlib = [	"curl", "reqwest", "path-absolutize"]
cmdline = ["cpclib-common/cmdline"]




