[package]

name = "cpclib"
version = "0.4.4"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Set of tools and libraries to ease demomaking on the Amstrad CPC platform. WIP"

repository = "https://github.com/cpcsdk/rust.cpclib"
readme = "Readme.mkd"
keywords = ["amstrad", "demo", "z80", "dsk" ,"sna"]
categories = ["command-line-utilities", "development-tools", "emulators"]


[dependencies]

cpclib-basic = "0.4.4"
cpclib-sna = "0.4.4"
cpclib-asm = "0.4.4"
cpclib-z80emu = "0.4.4"
cpclib-xfer = "0.4.4"
cpclib-disc = "0.4.4"
cpclib-macros = "0.4.4"

anyhow = "1.0.40"
arrayref= "0.3.6"
as-slice = "0.2.1"
bitfield = "0.13.2"
bitflags = "1.2.1"
bitsets = "0.1.1"
cfg-if = "1.0.0"
custom_error = "1.9.2"
dbg = "1.0.4"
delegate = "0.5.1"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.1"
gif = "0.11.2"
gif-dispose = "3.1.1"
image = "0.23.14"
itertools= "0.10.0"
lazy_static= "1.4.0"
matches = "0.1.8"
memchr = "2.3.4"
nom = "6.1.2"
num_enum = "0.5.1"
num= "0.4.0"
paste = "1.0.5"
serde = { version = "1.0.125", features = ["derive"] }
smallvec = "1.6.1"
strsim = "0.10.0"
tempfile= "3.2.0"



semver = { version = "0.11.0", optional = true }

path-absolutize = { version = "3.0.7", optional = true }
curl = { version = "0.4.35", optional = true }
reqwest = { version = "0.11.3", optional = true }

clap = { version = "2.33.3", optional = true }
time = { version = "0.2.26", optional = true }
exitcode = { version = "1.1.2", optional = true }

lz4 = { version = "1.23.2", optional = true }



notify = { version = "5.0.0-pre.6", optional = true }
crossbeam-channel = { version = "0.5.1", optional = true }

log = { version = "0.4.14", optional = true }

[dev-dependencies] 
pretty_assertions= "0.7.1"

[build-dependencies]
built = { version = "0.4.4", features = ["chrono"] }


[features]
xferlib = [	"curl", "reqwest", "path-absolutize"]
imgconverter = ["clap", 'notify', "exitcode", "lz4"]




[[bin]]
name = "imgconverter"
path = "src/bin/imgconverter.rs"
#required-features = ["xferlib", "imgconverter"]
required-features = ["imgconverter"]

