[package]

name = "cpclib"
version = "0.5.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Set of tools and libraries to ease demomaking on the Amstrad CPC platform. WIP"

repository = "https://github.com/cpcsdk/rust.cpclib"
readme = "Readme.mkd"
keywords = ["amstrad", "demo", "z80", "dsk" ,"sna"]
categories = ["command-line-utilities", "development-tools", "emulators"]

[package.metadata.workspaces]
independent = true

[dependencies]

cpclib-basic = "0.5.0"
cpclib-sna = "0.5.0"


cpclib-asm = "0.5.0"
cpclib-z80emu = "0.5.0"
cpclib-xfer = "0.5.0"
cpclib-disc = "0.5.0"
cpclib-macros = "0.5.0"
cpclib-common = "0.5.0"
cpclib-image = "0.5.0"

anyhow = "1.0.57"
arrayref= "0.3.6"
cfg-if = "1.0.0"
custom_error = "1.9.2"
dbg = "1.0.4"
delegate = "0.6.2"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.2"

matches = "0.1.9"
#memchr = "2.4.0"
paste = "1.0.7"
serde = { version = "1.0.136", features = ["derive"] }
tempfile= "3.3.0"




path-absolutize = { version = "3.0.13", optional = true }
curl = { version = "0.4.43", optional = true }
reqwest = { version = "0.11.10", optional = true }

time = { version = "0.3.9", optional = true }



log = { version = "0.4.16", optional = true }




[dev-dependencies] 
pretty_assertions= "1.2.1"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }


[features]
default = ["xferlib"]
xferlib = [	"curl", "reqwest", "path-absolutize"]
cmdline = ["cpclib-common/cmdline"]




