[package]
name = "cpc"
version = "0.2.0"
authors = ["Romain Giot <giot.romain@gmail.com"]
edition = "2018"

[dependencies]
num="0.1.42"
image = "0.20.1"
vecmath = "0.3.1"
matches = "0.1.8"
lazy_static= "1.2.0"
memchr = "2.1.1"
smallvec = "0.6.6"
itertools="0.7.8"
bitsets = "0.1.1"
bitflags = "*"

[dependencies.nom]
version = "4.1.1"
#features = ["verbose-errors"]
