[package]

name = "cpclib"
version = "0.10.0"
description = "Set of tools and libraries to ease demomaking on the Amstrad CPC platform. WIP"
keywords = ["amstrad", "demo", "z80", "dsk" ,"sna"]
categories = ["command-line-utilities", "development-tools", "emulators"]
readme = "Readme.mkd"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]

cpclib-basic.workspace = true
cpclib-sna.workspace = true
cpclib-crunchers.workspace = true
cpclib-asm.workspace = true
cpclib-z80emu.workspace = true
cpclib-xfer = {workspace = true, optional= true}
cpclib-disc.workspace = true
cpclib-macros.workspace = true
cpclib-common.workspace = true
cpclib-image.workspace = true

anyhow.workspace = true
arrayref.workspace = true
cfg-if.workspace = true
custom_error.workspace = true
dbg.workspace = true
delegate.workspace = true
either.workspace = true
getset.workspace = true
log = { workspace = true, optional = true }
paste.workspace = true
path-absolutize = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
camino-tempfile.workspace = true
time = { workspace = true, optional = true }




[dev-dependencies] 
pretty_assertions= "1.4.1"

[build-dependencies]
built = { workspace = true, features = ["chrono"] }


[features]
default = ["xferlib"]
xferlib = ["cpclib-xfer"]
cmdline = ["cpclib-common/cmdline"]




