[package]
name = "cpclib-visual-bndbuild"
version = "0.2.1"
resolver = "2"

description = "Amstrad CPC project builder. Biased towards basm, but can still work with any tool. This is the graphical version."


authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
cpclib-bndbuild.workspace = true
eframe = {workspace=true, features=["persistence"]}
egui_code_editor = "0.1.7"
egui_file = "0.10"
gag = "1.0.0"
serde.workspace = true
itertools.workspace = true
env_logger = "0.10"
self_cell = "1.0.1"
open = "5.0.0"
notify = "6.1.1"
catppuccin-egui = "3.1.0"

[build-dependencies]
built = { version = "0.6.1", features = ["chrono"] }
static_vcruntime = "2.0"
