[package]
name = "cpclib-visual-bndbuild"
version = "0.2.0"
resolver = "2"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
cpclib-bndbuild.workspace = true
eframe = {workspace=true, features=["persistence"]}
egui_code_editor = "0.1.3"
egui_file = "0.10"
gag = "1.0.0"
serde.workspace = true
itertools.workspace = true
env_logger = "0.10"
self_cell = "1.0.1"
open = "5.0.0"

[build-dependencies]
built = { version = "0.6.1", features = ["chrono"] }
static_vcruntime = "2.0"
