[package]
name = "cpclib-visual-bndbuild"
version = "0.5.0"
resolver = "2"

description = "Amstrad CPC project builder. Biased towards basm, but can still work with any tool. This is the graphical version."


authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-bndbuild.workspace = true
cpclib-common = {workspace=true, features=["cmdline"]}

camino = {workspace=true, features=["serde1"]}
eframe = {workspace=true, features=["persistence"]}
egui_file.workspace = true
env_logger.workspace = true
gag.workspace = true
itertools.workspace = true
open.workspace = true
self_cell.workspace = true
serde.workspace = true

[build-dependencies]
built = { version = "0.7.7", features = ["chrono"] }
static_vcruntime = "2.0"

[features]
default = []
rayon = ["cpclib-bndbuild/rayon"]
hfe = ["cpclib-bndbuild/hfe"]

[[bin]]
name = "bndbuild-gui"
path = "src/main.rs"

