[package]
name = "cpclib-visual-bndbuild"
version = "0.2.1"
resolver = "2"

description = "Amstrad CPC project builder. Biased towards basm, but can still work with any tool. This is the graphical version."


authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
catppuccin-egui.workspace = true
cpclib-bndbuild.workspace = true
eframe = {workspace=true, features=["persistence"]}
egui_file.workspace = true
env_logger.workspace = true
gag.workspace = true
itertools.workspace = true
notify.workspace = true
open.workspace = true
self_cell.workspace = true
serde.workspace = true
egui_code_editor.workspace = true

[build-dependencies]
built = { version = "0.6.1", features = ["chrono"] }
static_vcruntime = "2.0"
