[package]
name = "cpclib-bndbuild-tauri"
version.workspace = true
description = "Tauri GUI of bndbuild"


authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "bndbuild_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[build-dependencies]
tauri-build = { workspace = true, features = [] }
fs-err.workspace = true

[target."cfg(windows)".build-dependencies]
ureq.workspace = true
zip.workspace = true

[dependencies]
cpclib-bndbuild.workspace = true
cfg-if.workspace = true

camino = {workspace=true, features = ["serde1"] }
gag.workspace = true
log.workspace = true
serde = {workspace=true, features = ["derive"] }
serde_json.workspace = true
tauri = { workspace = true, features = ["devtools"] }

tauri-plugin-dialog.workspace = true
tauri-plugin-fs.workspace = true
tauri-plugin-log.workspace = true
tauri-plugin-notification.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-persisted-scope.workspace = true
tauri-plugin-shell.workspace = true
tauri-plugin-store.workspace = true
#tauri-plugin-devtools = "2.0.0"
#tauri-plugin-devtools-app = "2.0.0"


[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state.workspace = true


[profile.dev]
incremental = true # Compile your binary in smaller steps.


[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.

[features]
default = ["rayon"]
rayon = ["cpclib-bndbuild/rayon"] # in fact i don't wont to accept it, it is jsut a workaround to avoid linter to force rayon specific arguments...
