[package]
name = "cpclib-sna"
version = "0.6.1-alpha.1"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-common = "0.6.0"

cfg-if = "1.0.0"
delegate  = "0.6.2"
matches = "0.1.9"
#minus = {git="https://github.com/arijit79/minus.git", branch="use-parking_lot", features=["static_output"]}
minus = {version="5.2.0", features=["static_output"]}
serde = { version = "1.0.137", features = ["derive"] }
num_enum = "0.5.7"

rustyline = { version ="9.1.2", optional = true}

[dev-dependencies]
tempfile = "3.3.0"
similar-asserts = "1.2.0"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }

[features]
default = ["snapshot"]
snapshot = ["cpclib-common/cmdline", "rustyline"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
