[package]
name = "cpclib-sna"
version = "0.4.1-alpha"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
bitflags = "1.2.1"
bitsets = "0.1.1"
cfg-if = "0.1.10"
matches = "0.1.8"
num_enum = "0.4.2"
serde = { version = "1.0.103", features = ["derive"] }
smallvec = "1.0.0"
strsim = "0.9.2"

clap = { version = "2.33.0", optional = true }
time = { version = "0.1.42", optional = true }
semver = { version = "0.9.0", optional = true }

[build-dependencies]
built = {version = "0.4", features = ["chrono"]}

[features]
snapshot = ["clap", "time", "semver"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
