[package]
name = "cpclib-sna"
version = "0.8.1"
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-common.workspace = true

cfg-if.workspace = true
delegate.workspace = true
matches.workspace = true
serde.workspace = true
num_enum.workspace = true
comfy-table = {version="7.1.1", optional = true}
line-span = "0.1.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustyline = { workspace = true, optional = true}
minus = {workspace=true, optional = true}

[dev-dependencies]
tempfile.workspace = true
similar-asserts.workspace = true

[build-dependencies]
built.workspace = true

[features]
default = []
snapshot = ["cpclib-common/cmdline", "rustyline", "minus", "comfy-table"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
