[package]
name = "cpclib-sna"
version = "0.4.4"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
bitflags = "1.2.1"
bitsets = "0.1.1"
cfg-if = "1.0.0"
matches = "0.1.8"
num_enum = "0.5.1"
serde = { version = "1.0.125", features = ["derive"] }
smallvec = "1.6.1"
strsim = "0.10.0"
nom = "6.1.2"


clap = { version = "2.33.3", optional = true }
time = { version = "0.2.26", optional = true }
semver = { version = "0.11.0", optional = true }

[build-dependencies]
built = { version = "0.4.4", features = ["chrono"] }

[features]
snapshot = ["clap", "time", "semver"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
