[package]
name = "cpclib-sna"
version = "0.6.1-alpha.2"
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-common = "0.6.1-alpha.2"

cfg-if.workspace = true
delegate.workspace = true
matches.workspace = true
minus.workspace = true
serde.workspace = true
num_enum.workspace = true

rustyline = { workspace = true, optional = true}

[dev-dependencies]
tempfile.workspace = true
similar-asserts.workspace = true

[build-dependencies]
built.workspace = true

[features]
default = ["snapshot"]
snapshot = ["cpclib-common/cmdline", "rustyline"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
