[package]
name = "cpclib-sna"
version = "0.5.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib libraries related to snapshots"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
cpclib-common = "0.5.0"

cfg-if = "1.0.0"
matches = "0.1.8"
serde = { version = "1.0.126", features = ["derive"] }
num_enum = "0.5.4"


[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }

[features]
default = ["snapshot"]
snapshot = ["cpclib-common/cmdline"]


[[bin]]
name = "snapshot"
path = "src/bin/snapshot.rs"
required-features = ["snapshot"]
