[package]

name = "cpclib-asm"
version = "0.6.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib libraries related to z80 assembling"
repository = "https://github.com/cpcsdk/rust.cpclib"

[package.metadata.workspaces]
independent = true

[dependencies]


cpclib-basic = "0.6.0"
cpclib-sna = "0.6.0"
cpclib-tokens = "0.6.0"
cpclib-disc = "0.6.0"
cpclib-common = "0.6.0"
cpclib-image = "0.6.0"
cpclib-xfer = "0.6.0"


#humantime = "2.1.0"
#memchr = "2.4.0"
#phf = {version="0.9.0", features=["macros"]} // unable to use as I whish
arrayref= "0.3.6"
cfg-if = "1.0.0"
chardet = "0.2.4"
codespan-reporting = "0.11.1"
custom_error = "1.9.2"
delegate = "0.6.2"
either = "1.6.1"
encoding = "0.2.33"
failure = "0.1.8"
getset = "0.1.2"
globset = "0.4.8"
indicatif = "0.17.0-rc.10"
lazy_static = "1.4.0"
libc = "0.2.124"
matches = "0.1.9"
ouroboros = "0.15.0"
paste = "1.0.7"
regex = "1.5.5"
rust-embed = { version="6.4.0", features = ["compression"] }
serde = { version = "1.0.136", features = ["derive"] }
substring = "1.4.5"
velcro = "0.5.3"
assert_matches = "1.5.0"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }
cc = "1.0.73"

#[lib]
#crate-type = ["cdylib", "dylib"]


[features]
default = ["colored_errors"]
basm = ["cpclib-common/cmdline"] #only usefull for the basm crate
colored_errors = []


