[package]

name = "cpclib-asm"
version = "0.4.4"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib libraries related to assembling"
repository = "https://github.com/cpcsdk/rust.cpclib"


[dependencies]


cpclib-basic = "0.4.4"
cpclib-sna = "0.4.4"
cpclib-tokens = "0.4.4"
cpclib-disc = "0.4.4"


arrayref= "0.3.6"
bitfield = "0.13.2"
bitflags = "1.2.1"
bitsets = "0.1.1"
chardet = "0.2.4"
cfg-if = "1.0.0"
custom_error = "1.9.2"
delegate = "0.5.1"
encoding = "0.2.33"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.1"
itertools= "0.10.0"
matches = "0.1.8"
memchr = "2.4.0"
nom = "6.1.2"
num_enum = "0.5.1"
paste = "1.0.5"
rayon = "1.5.0"
serde = { version = "1.0.125", features = ["derive"] }
smallvec = "1.6.1"
strsim = "0.10.0"
libc = "0.2.94"


time = { version = "0.2.26", optional = true }
semver = { version = "0.11.0", optional = true }
clap = { version = "2.33.3", optional = true }


[build-dependencies]
built = { version = "0.5.0", features = ["chrono"] }
cc = "1.0.67"

#[lib]
#crate-type = ["cdylib", "dylib"]


[features]
basm = ["clap",  "semver", "time"]
bdasm = ["clap",  "semver", "time"]

[[bin]]
name = "basm"
path = "src/bin/basm.rs"
required-features = ["basm"]

[[bin]]
name = "bdasm"
path = "src/bin/bdasm.rs"
required-features = ["bdasm"]

