[package]

name = "cpclib-asm"
version = "0.5.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib libraries related to assembling"
repository = "https://github.com/cpcsdk/rust.cpclib"


[dependencies]


cpclib-basic = "0.5.0"
cpclib-sna = "0.5.0"
cpclib-tokens = "0.5.0"
cpclib-disc = "0.5.0"
cpclib-common = "0.5.0"
cpclib-image = "0.5.0"


#humantime = "2.1.0"
#memchr = "2.4.0"
#phf = {version="0.9.0", features=["macros"]} // unable to use as I whish
arrayref= "0.3.6"
cfg-if = "1.0.0"
chardet = "0.2.4"
codespan-reporting = "0.11.1"
custom_error = "1.9.2"
delegate = "0.5.2"
either = "1.6.1"
encoding = "0.2.33"
failure = "0.1.8"
getset = "0.1.1"
globset = "0.4.8"
libc = "0.2.97"
matches = "0.1.8"
paste = "1.0.5"
rayon = "1.5.1"
serde = { version = "1.0.126", features = ["derive"] }
substring = "1.4.5"



[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }
cc = "1.0.68"

#[lib]
#crate-type = ["cdylib", "dylib"]


[features]
basm = ["cpclib-common/cmdline"] #only usefull for the basm crate
nocolor = []


