[package]
name = "cpclib-emucontrol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
cpclib-runner.workspace = true
cpclib-common.workspace = true
cpclib-csl.workspace = true
clap = {workspace=true, features=["derive"]}
glob.workspace = true



[dev-dependencies]
assert_cmd.workspace = true
serial_test.workspace = true
ntest.workspace = true

[[bin]]
name = "emucontrol"
path = "src/main.rs"


[features]
default = ["screenshot"]
screenshot = ["cpclib-runner/screenshot"]
