[package]

name = "cpclib-xfertool"
version = "0.3.2-alpha"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib tool related to xfer"

[dependencies]
cpclib-disc = "0.3.2-alpha"
cpclib-sna = "0.3.2-alpha"
cpclib-xfer = "0.3.2-alpha"


anyhow = "1.0"
arrayref= "0.3.5"
bitfield = "0.13.2"
bitflags = "1.2.1"
bitsets = "0.1.1"
cfg-if = "0.1.10"
custom_error = "1.7.1"
delegate = "0.3.0"
either = "1.5.3"
failure = "0.1.6"
getset = "0.0.9"
itertools= "0.8.2"
lazy_static= "1.4.0"
matches = "0.1.8"
memchr = "2.2.1"
nom = "5.0.1"
num_enum = "0.4.2"
serde = { version = "1.0.103", features = ["derive"] }
smallvec = "1.0.0"
strsim = "0.9.2"
tempfile= "3.1.0"

path-absolutize = { version = "1.1.7", optional = false }
curl = { version = "0.4.25", optional = false }
reqwest = { version = "0.9.22", optional = false }


clap = { version = "2.33.0", optional = false }
time = { version = "0.1.42", optional = false }

rustyline = { version = "6.0.0", optional = false }
rustyline-derive = {version="0.3.0", optional= false}
subprocess = {version="0.2.4", optional=false}
notify = { version = "5.0.0-pre.2", optional = false }
crossbeam-channel = { version = "0.4.0", optional = false }
hotwatch = { version = "0.4.3", optional = false }


term_grid = {version="0.1.7", optional= false}
termize = {version="0.1.1", optional= false}

[build-dependencies]
built = {version = "0.4", features = ["chrono"]}


