[package]

name = "cpclib-xfertool"
version = "0.6.0"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2021"
license = "MIT"
description = "cpclib tool related to xfer"
repository = "https://github.com/cpcsdk/rust.cpclib"

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-disc = "0.6.0"
cpclib-sna = "0.6.0"
cpclib-xfer = "0.6.0"
cpclib-common = "0.6.0"


anyhow = "1.0.57"
arrayref= "0.3.6"
cfg-if = "1.0.0"
custom_error = "1.9.2"
delegate = "0.6.2"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.2"
lazy_static= "1.4.0"
matches = "0.1.9"
#memchr = "2.4.0"
serde = { version = "1.0.137", features = ["derive"] }
tempfile= "3.3.0"

path-absolutize = { version = "3.0.13", optional = false }
curl = { version = "0.4.43", optional = false }
reqwest = { version = "0.11.10", optional = false }


time = { version = "0.3.9", optional = false }

rustyline = { version = "9.1.2", optional = false }
rustyline-derive = { version = "0.6.0", optional = false }
subprocess = { version = "0.2.9", optional = false }
notify = { version = "5.0.0-pre.15", optional = false }
crossbeam-channel = { version = "0.5.4", optional = false }
hotwatch = { version = "0.4.6", optional = false }


term_grid = { version = "0.2.0", optional = false }
termize = { version = "0.1.1", optional = false }

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }


