[package]

name = "cpclib-xfertool"
version = "0.8.0"
description = "cpclib tool related to xfer"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-disc.workspace = true
cpclib-sna.workspace = true
cpclib-xfer.workspace = true
cpclib-common = {workspace = true, features = ["cmdline"]}


anyhow.workspace = true
arrayref.workspace = true
cfg-if.workspace = true
custom_error.workspace = true
delegate.workspace = true
either.workspace = true
getset.workspace = true
matches.workspace = true
serde = { workspace = true, features = ["derive"] }
tempfile.workspace = true

path-absolutize = {workspace = true, optional = false }
curl = {workspace = true, optional = false }


time.workspace = true

rustyline = {  workspace = true, optional = true }
rustyline-derive = {  workspace = true, optional = true }

subprocess = {  workspace = true, optional = false }

notify = { workspace = true, optional = true }
crossbeam-channel = {  workspace = true, optional = true }
hotwatch = {  workspace = true, optional = true }


term_grid = {  workspace = true, optional = false }
termize = { workspace = true, optional = false }


[features]
default = ["interactive", "watch"]
interactive = ["rustyline", "rustyline-derive"]
watch = ["notify", "crossbeam-channel", "hotwatch"]

[build-dependencies]
built.workspace = true


