[package]

name = "cpclib-xfertool"
version = "0.4.4"
authors = ["Romain Giot <giot.romain@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cpclib tool related to xfer"
repository = "https://github.com/cpcsdk/rust.cpclib"

[dependencies]
cpclib-disc = "0.4.4"
cpclib-sna = "0.4.4"
cpclib-xfer = "0.4.4"


anyhow = "1.0.40"
arrayref= "0.3.6"
bitfield = "0.13.2"
bitflags = "1.2.1"
bitsets = "0.1.1"
cfg-if = "1.0.0"
custom_error = "1.8.0"
delegate = "0.5.1"
either = "1.6.1"
failure = "0.1.8"
getset = "0.1.1"
itertools= "0.10.0"
lazy_static= "1.4.0"
matches = "0.1.8"
memchr = "2.3.4"
nom = "6.1.2"
num_enum = "0.5.1"
serde = { version = "1.0.125", features = ["derive"] }
smallvec = "1.6.1"
strsim = "0.10.0"
tempfile= "3.2.0"

path-absolutize = { version = "3.0.7", optional = false }
curl = { version = "0.4.35", optional = false }
reqwest = { version = "0.11.2", optional = false }


clap = { version = "2.33.3", optional = false }
time = { version = "0.2.26", optional = false }

rustyline = { version = "8.0.0", optional = false }
rustyline-derive = { version = "0.4.0", optional = false }
subprocess = { version = "0.2.6", optional = false }
notify = { version = "5.0.0-pre.6", optional = false }
crossbeam-channel = { version = "0.5.0", optional = false }
hotwatch = { version = "0.4.5", optional = false }


term_grid = { version = "0.2.0", optional = false }
termize = { version = "0.1.1", optional = false }

[build-dependencies]
built = { version = "0.4.4", features = ["chrono"] }


