;;
; PROVIDES SEVERAL SYMBOLIC VARIABLES THAT CAN EASE CRTC CODE WRITTING


__BASM__INNER__CRTC__

CRTC_REG_COUNTER = 0



CRTC_REG0 NEXT CRTC_REG_COUNTER
CRTC_REG1 NEXT CRTC_REG_COUNTER
CRTC_REG2 NEXT CRTC_REG_COUNTER
CRTC_REG3 NEXT CRTC_REG_COUNTER
CRTC_REG4 NEXT CRTC_REG_COUNTER
CRTC_REG5 NEXT CRTC_REG_COUNTER
CRTC_REG6 NEXT CRTC_REG_COUNTER
CRTC_REG7 NEXT CRTC_REG_COUNTER
CRTC_REG8 NEXT CRTC_REG_COUNTER
CRTC_REG9 NEXT CRTC_REG_COUNTER
CRTC_REG10 NEXT CRTC_REG_COUNTER
CRTC_REG11 NEXT CRTC_REG_COUNTER
CRTC_REG12 NEXT CRTC_REG_COUNTER
CRTC_REG13 NEXT CRTC_REG_COUNTER
CRTC_REG14 NEXT CRTC_REG_COUNTER
CRTC_REG15 NEXT CRTC_REG_COUNTER
CRTC_REG16 NEXT CRTC_REG_COUNTER
CRTC_REG17 NEXT CRTC_REG_COUNTER

; I use these indirection to ease vscode integration and have a usefull thing to show on overlay

CRTC_REG_HORIZONTAL_TOTAL equ CRTC_REG0
CRTC_REG_HORIZONTAL_DISPLAYED equ CRTC_REG1
CRTC_REG_HORIZONTAL_SYNC_POSITION equ CRTC_REG2
CRTC_REG_HORIZONTAL_AND_VERTICAL_SYNC_WIDTHS equ CRTC_REG3
CRTC_REG_VERTICAL_TOTAL equ CRTC_REG4
CRTC_REG_VERTICAL_TOTAL_ADJUST equ CRTC_REG5
CRTC_REG_VERTICAL_DISPLAYED equ CRTC_REG6
CRTC_REG_VERTICAL_SYNC_POSITION equ CRTC_REG7
CRTC_REG_INTERLACE_AND_SKEW equ CRTC_REG8
CRTC_REG_MAXIMUM_RASTER_ADDRESS equ CRTC_REG9
CRTC_REG_CURSOR_START_RASTER equ CRTC_REG10
CRTC_REG_CURSOR_END_RASTER equ CRTC_REG11
CRTC_REG_DISPLAY_START_ADDRESS_HIGH equ CRTC_REG12
CRTC_REG_DISPLAY_START_ADDRESS_LOW equ CRTC_REG13
CRTC_REG_CURSOR_ADDRESS_HIGH equ CRTC_REG14
CRTC_REG_CURSOR_ADDRESS_LOW equ CRTC_REG15
CRTC_REG_LIGHT_PEN_ADDRESS_HIGH equ CRTC_REG16
CRTC_REG_LIGHT_PEN_ADDRESS_LOW equ CRTC_REG17

    assert CRTC_REG_HORIZONTAL_TOTAL == 0, "There is a bug in the assembler"
    assert CRTC_REG_LIGHT_PEN_ADDRESS_LOW == 17, "There is a bug in the assembler"


CRTC_DEFAULT_FOR_HORIZONTAL_TOTAL equ 63
CRTC_DEFAULT_FOR_HORIZONTAL_DISPLAYED equ 40
CRTC_DEFAULT_FOR_HORIZONTAL_SYNC_POSITION equ 46
CRTC_DEFAULT_FOR_HORIZONTAL_AND_VERTICAL_SYNC_WIDTHS equ 128 + 14
CRTC_DEFAULT_FOR_VERTICAL_TOTAL equ 38
CRTC_DEFAULT_FOR_VERTICAL_TOTAL_ADJUST equ 0
CRTC_DEFAULT_FOR_VERTICAL_DISPLAYED equ 25
CRTC_DEFAULT_FOR_VERTICAL_SYNC_POSITION equ 30
CRTC_DEFAULT_FOR_INTERLACE_AND_SKEW equ 0
CRTC_DEFAULT_FOR_MAXIMUM_RASTER_ADDRESS equ 7
CRTC_DEFAULT_FOR_CURSOR_START_RASTER equ 0
CRTC_DEFAULT_FOR_CURSOR_END_RASTER equ 0
CRTC_DEFAULT_FOR_DISPLAY_START_ADDRESS_HIGH equ 48
CRTC_DEFAULT_FOR_DISPLAY_START_ADDRESS_LOW equ 0
CRTC_DEFAULT_FOR_CURSOR_ADDRESS_HIGH equ 0
CRTC_DEFAULT_FOR_CURSOR_ADDRESS_LOW equ 0
;CRTC_DEFAULT_FOR_LIGHT_PEN_ADDRESS_HIGH ; read only
;CRTC_DEFAULT_FOR_LIGHT_PEN_ADDRESS_LOW  ; read only