[package]
name = "cpclib-imgconverter"
version = "0.6.0"
edition = "2021"
description = "Image manipulation tool for amstrad CPC"
repository = "https://github.com/cpcsdk/rust.cpclib"
license = "MIT"

[package.metadata.workspaces]
independent = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpclib = { version = "0.6.0", features = ["cmdline"] }

lz4 = "1.23.3"
notify = "5.0.0-pre.14"
crossbeam-channel = "0.5.4"
exitcode = "1.1.2"
tempfile= "3.3.0"
anyhow = "1.0.57"

[build-dependencies]
built = { version = "0.5.1", features = ["chrono"] }

[features]
default = ["xferlib"]
xferlib = ["cpclib/xferlib"]


[[bin]]
name = "imgconverter"
path = "src/main.rs"
