[package]
name = "cpclib-rasm-basm-tests"
version.workspace = true
edition.workspace = true

[dependencies]
walkdir = { workspace = true }
camino-tempfile = { workspace = true }
cpclib-bndbuild = { workspace = true }
anyhow = { workspace = true }
fs-err = { workspace = true }

[dev-dependencies]
test-generator.workspace = true

[build-dependencies]
build-deps.workspace = true
